_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.8.0
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
                - 80
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
                - 74
                - 80
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.8.0
            "5": 0.19.10
            "8":
                - 1
                - 5
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 50
